module.exports = {
  rules: {
    'array-bracket-newline': ['error', 'consistent'],
    'array-element-newline': ['error', 'consistent'],
    'arrow-spacing': 'error',
    'block-spacing': 'error',
    'brace-style': 'error',
    'camelcase': ['error', { 'allow': ['^UNSAFE_'] }],
    // Sometimes you want to start a comment with the name of a variable
    'capitalized-comments': 'off',
    'comma-dangle': ['error', 'always-multiline'],
    'comma-spacing': 'error',
    'comma-style': 'error',
    'computed-property-spacing': 'error',
    'curly': 'error',
    'default-case-last': 'error',
    'dot-location': ['error', 'property'],
    'dot-notation': 'error',
    'eol-last': 'error',
    'func-call-spacing': 'error',
    'func-name-matching': 'off',
    'func-names': ['error', 'as-needed'],
    'func-style': 'error',
    'function-call-argument-newline': ['error', 'consistent'],
    'function-paren-newline': ['error', 'consistent'],
    'generator-star-spacing': 'error',
    'grouped-accessor-pairs': ['error', 'getBeforeSet'],
    'id-denylist': 'off',
    'id-length': 'off',
    'id-match': 'off',
    'implicit-arrow-linebreak': 'error',
    'indent': ['error', 2],
    'jsx-quotes': 'error',
    'keyword-spacing': 'error',
    'linebreak-style': ['error', 'unix'],
    'max-classes-per-file': 'error',
    'max-depth': ['warn', 4],
    'max-len': [
      'warn',
      {
        'code': 120,
        'ignoreRegExpLiterals': true,
        'ignoreStrings': true,
        'ignoreTemplateLiterals': true,
        'ignoreUrls': true,
      },
    ],
    'max-statements-per-line': ['error', { 'max': 1 }],
    'new-cap': 'error',
    'newline-per-chained-call': 'error',
    'no-continue': 'error',
    'no-irregular-whitespace': 'error',
    'no-lonely-if': 'error',
    'no-mixed-spaces-and-tabs': 'error',
    'no-multiple-empty-lines': 'error',
    'no-tabs': 'error',
    'no-trailing-spaces': 'error',
    'no-unneeded-ternary': 'error',
    'object-curly-spacing': ['error', 'always'],
    'one-var-declaration-per-line': 'error',
    'quotes': ['error', 'single'],
    // This rule is wonky with single combined with multiple
    'sort-imports': 'off',
    'sort-keys': 'error',
    'sort-vars': 'error',
  },
};
